#
# Ports:
# 9042         Cassandra
# 9200         Elastic HTTP
# 9300         Elastic Transport
# 9092         Kafka Broker
# 3030         Kafka Explorer
# 9090         Prometheus
# 3000         Grafana
#

version: '3'
services:

  kafka:
    container_name: kafka
    image: landoop/fast-data-dev:latest
    ports:
      - "2181:2181"
      - "3030:3030"
      - "9092:9092"
      - "8081-8083:8081-8083"
    environment:
      RUNTESTS: 0
      SAMPLEDATA: 0
      FORWARDLOGS: 0
      ADV_HOST: kafka

  elassandra:
    container_name: elassandra
    image: strapdata/elassandra:5.5.0.13
    environment:
      CASSANDRA_DC: DC1
      CASSANDRA_CLUSTER_NAME: CYBER_SEARCH
    ports:
      - "9200:9200"
      - "9042:9042"

  prometheus:
    container_name: prometheus
    restart: on-failure
    image: prom/prometheus:v2.2.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    restart: on-failure
    image: grafana/grafana:5.1.3
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-dashboards:/etc/grafana/provisioning/

  bitcoind:
    container_name: bitcoind
    build: ./docker/bitcoind
    # image: ruimarinho/bitcoin-core:0.15.1
    ports:
      - "8332:8332"
      - "18332:18332"
    restart: on-failure
    entrypoint: bash -c "bitcoind -server -rest -txindex -rpcpasssword=cyber -rpcuser=cyber -rpcallowip=0.0.0.0/0"
    # entrypoint: bash -c "bitcoind -server -rest -printtoconsole -testnet -txindex -rpcpasssword=cyber -rpcuser=cyber -rpcallowip=0.0.0.0/0 | tee /home/bitcoin/.bitcoin/debug.log"
    # entrypoint: bash -c "while :; do echo 'Hit CTRL+C'; sleep 5; done"
    volumes:
      - .:/home/bitcoin/.bitcoin
      - ./.bitcoin:/root/.bitcoin

  pump:
    container_name: pump
    restart: on-failure
    build: ../pumps/bitcoin
    # image: cybernode/chain-pump-bitcoin:latest
    environment:
      CHAIN_FAMILY: BITCOIN
      CHAIN_NODE_URL: http://bitcoind:8332
      KAFKA_BROKERS: kafka:9092
      JAVA_OPTS: -Xdebug
    depends_on:
      # - bitcoind
      - kafka
    entrypoint: bash -c "java -Xdebug -jar /cyberapp/bin/bitcoin.jar"
    # entrypoint: bash -c "while :; do echo 'Hit CTRL+C'; sleep 5; done"
    # volumes:
      # - ./bin:/cyberapp/tmp

  dump:
    container_name: dump
    restart: on-failure
    image: cybernode/chain-dump-cassandra-bitcoin:latest
    environment:
      CHAIN_FAMILY: BITCOIN
      KAFKA_BROKERS: kafka:9092
      CASSANDRA_HOSTS: elassandra
    depends_on:
      - elassandra
      - kafka

  search-api:
    container_name: search-api
    restart: on-failure
    image: cybernode/search-api:latest
    environment:
      CASSANDRA_HOSTS: elassandra
    ports:
      - "8080:8080"
    depends_on:
      - elassandra
