global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'search-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pump:8080','dump:8080']
