#
# Ports:
# 9042         Cassandra
# 9200         Elastic HTTP
# 9300         Elastic Transport
# 9092         Kafka
# 3030         Kafka Explorer
# 9090         Prometheus
# 3000         Grafana
#

version: '3'
services:

  kafka:
    container_name: kafka
    image: landoop/fast-data-dev:latest
    ports:
#      - "2181:2181"
#      - "9581-9584:9581-9584"
      - "3030:3030"
      - "9092:9092"
      - "8081-8083:8081-8083"
    environment:
      RUNTESTS: 0
      SAMPLEDATA: 0
      FORWARDLOGS: 0
      ADV_HOST: kafka

  elassandra:
    container_name: elassandra
    image: strapdata/elassandra:5.5.0.13
    environment:
      CASSANDRA_DC: DC1
      CASSANDRA_CLUSTER_NAME: CYBER_SEARCH
    ports:
      - "9200:9200"
      - "9042:9042"

  prometheus:
    container_name: prometheus
    restart: on-failure
    image: prom/prometheus:v2.2.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    restart: on-failure
    image: grafana/grafana:5.1.3
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-dashboards:/etc/grafana/provisioning/

  parity:
    container_name: parity
    build: ./docker/parity
    # image: parity/parity:stable
    ports:
      - "8545:8545"
    entrypoint: bash -c "/parity/parity --db-path /cyberdata --log-file /cyberdata/parity.log --jsonrpc-hosts all --jsonrpc-interface all --jsonrpc-threads 4"
    volumes:
      -  .:/cyberdata
      -  ./.parity:/root/.local/share/io.parity.ethereum

  pump:
    container_name: pump-eth
    restart: on-failure
    build: ../pumps/ethereum
    # image: cybernode/chain-pump-ethereum:latest
    entrypoint: bash -c "java $JAVA_OPTS -jar /cyberapp/bin/ethereum.jar"
    # entrypoint: bash -c "while :; do echo 'Hit CTRL+C'; sleep 10; done"
    environment:
      CHAIN_FAMILY: ETHEREUM
      CHAIN_NODE_URL: http://parity:8545
      # CHAIN_NODE_URL: https://mainnet.infura.io/v3/67740b87160149309ac353f06891f986
      KAFKA_BROKERS: kafka:9092
    depends_on:
      # - parity
      - kafka

  dump:
    container_name: dump-eth
    restart: on-failure
    image: cybernode/chain-dump-cassandra-ethereum:latest
    environment:
      CHAIN_FAMILY: ETHEREUM
      KAFKA_BROKERS: kafka:9092
      CASSANDRA_HOSTS: elassandra
    depends_on:
      - elassandra
      - kafka

  search-api:
    container_name: search-api
    restart: on-failure
    image: cybernode/search-api:latest
    environment:
      CASSANDRA_HOSTS: elassandra
    ports:
      - "8080:8080"
    depends_on:
      - elassandra
